if(zapya==undefined||zapya==null){
	var zapya={};
}
zapya.language="cn";
zapya.langPkg={
	cn:{
		verify:{
			_1:"返回扫码页面",
			_2:"您已与手机断开连接！",
			_3:"手机",
			_4:"扫描二维码成功",
			_5:"请求连接成功，请在手机上确认！",
		},
		common:{
			_title:"快牙网传",
			_date:"日期",
			_0:"您即将删除选中文件",
			_1:"上传成功",
			_2:"上传失败，请重新尝试",
			_3:"全选",
			_4:"上传中，请稍候...",
			_5:"您即将删除选中图片",
			_6:"您即将删除选中视频",
			_7:"您即将删除选中音频",
			_8:"确认",
			_9:"取消",
			_10:"关闭",
			_11:"删除失败，请检查您的网络连接！",
			_12:"您即将删除选中文件",
			_13:"您的下载被浏览器阻拦，请设置地址栏出现的拦截设置",
			_14:"上传完成",
			_15:"个文件正在上传",
			_16:"快牙官网",
			_17:"重新连接",
		},
		button:{
			_0:"批量删除",
			_1:"批量下载",
			_2:"上传图片",
			_3:"上传视频",
			_4:"上传音乐",
		},
		homepage:{
			_0:"我的设备",
			_1:"图片",
			_2:"视频",
			_3:"音乐",
			_4:"应用游戏",
			_5:"文件管理",
			_6:"相机",
			_7:"支持拖拽上传"
		},
		device:{
			_0:"当前",
			_1:"共",
			_2:"您已与手机断开连接！",
		},
		images:{
			_0:"相册",
			_1:"快牙",
			_2:"其他",
			_3:"QQ",
			_4:"微信",
			_5:"微博",
			_6:"屏幕截图",
			_7:"蓝牙"
		},
		video:{
			_0:"视频",
			_1:"此视频格式暂不支持播放",
		},
		audio:{
			_0:"音乐",
			_1:"歌曲名",
			_2:"歌手",
			_3:"时长",
			_4:"格式",
			_5:"大小",
			_6:"当前播放列表已至最顶部",
			_7:"当前播放列表已至最底部",
			_8:"未知",
			_9:"专辑"
		},
		app:{
			_0:"名称",
			_1:"大小",
			_2:"应用",
			_3:"数据",
			_4:"全选",
			_5:"批量下载",
			_6:"上传安装包",
			_7:"卸载",
			_8:"删除",
			_9:"应用游戏",
			_10:"应用正在导入,请稍后在手机上点击安装.....",
			_11:"应用加载失败",
			_12:"请在手机上完成卸载",
			_13:"卸载操作失败",
			_14:"导入失败",
			_15:"下载",
			_16:"安装包大小",
			_17:"数据大小",
			_18:"缓存大小",
			_19:"版本号"

		},
		file:{
			_0:"文件类别",
			_1:"存储",
			_2:"最近文件",
			_3:"大文件",
			_4:"压缩文件",
			_5:"安装包",
			_6:"文档",
			_7:"内部存储",
			_8:"外部存储",
			_9:"名称",
			_10:"所在路径",
			_11:"大小",
			_12:"类型",
			_13:"日期",
			_14:"全选",
			_15:"删除",
			_16:"批量下载",
			_17:"上传文件",
			_18:"新建文件夹",
			_19:"文件正在导入,请稍候.....",
			_20:"删除失败",
			_21:"导入失败",
			_22:"新建文件夹失败",
			_23:"文件夹名字不能为空",
			_24:"文件夹和已有文件重名",
			_25:"下载失败",
			_26:"下载",
			_27:"文件加载失败",
			_28:"批量删除",
			_29:"QQ",
			_30:"微信"

		},
		camera:{
			_0:"打开相机失败",
			_1:"预览",
			_2:"停止预览",
			_3:"开启闪光灯",
			_4:"关闭闪光灯",
			_5:"操作失败",
			_6:"拍照成功",
			_7:"拍照失败",
			_8:"拍照",
			_9:"反转摄像头",
			_10:"设置",
			_11:"存储到电脑",
			_12:"存储到手机",
			_13:"自动聚焦",
			_14:"拍照前自动聚焦",
			_15:"设置成功",
			_16:"设置失败",
			_17:"发送成功",
			_18:"发送失败",
			_19:"允许通知",
			_20:"禁止通知",
			_21:"请开启预览后点击拍照!",
			_22:"、如果打开相机失败，请在手机系统应用权限设置中允许快牙网传使用相机，并查看相机是否被其它应用占用。",
			_23:"、点击相机界面右下角的按钮可以开启／关闭相机，相机打开时，会导致其它应用无法使用相机。",
			_24:"、拍照后，保存到手机的照片可以在快牙网传app的侧边栏->网传相册中查看。",
			_25:"、预览、拍照的效果与相机、网络质量有关。",
			_26:"切镜头",
			_27:"帮助",
			_28:"辅助构图线",
			_29:"图片保存位置",
			_30:"图片比例",
			_31:"闪光灯",
			_32:"图片质量",
			_33:"提升图片质量会降低预览的流畅度",
			_34:"差",
			_35:"模糊",
			_36:"一般",
			_37:"较好",
			_38:"清晰"
		},
		pasteboard:{
			_0:"剪粘板",
			_1:"搜索",
			_2:"发送",
			_3:"发送内容到手机的粘贴板，长按编辑区域可以粘贴内容",
			_4:"在手机的浏览器中打开网页或搜索内容",
			_5:"在浏览器中打开",
			_6:"清除"
		},
		message:{
			_0:"共",
			_1:"条消息",
			_2:"点击",
			_3:"查看",
			_4:"在快牙网传app侧边栏->设置中开启桌面通知服务后，手机收到的通知会显示在这里。",
			_5:"通知栏",
			_6:"在快牙网传app侧边栏->设置中开启桌面通知服务后，手机收到的来电、短信会显示在这里。",
			_7:"通知"
		},
		upload:{
			_0:"拖拽文件到这里上传",
			_1:" 个文件已上传",
			_2:" 个文件上传失败",
			_3:" 个文件已上传",
			_4:" 个文件上传失败"
		},
		phone:{
			_0:"编辑",
			_1:"首页",
			_2:"文件上传",
			_3:"主页",
			_4:"手机内存",
			_5:"存储到远程设备",
			_6:"按歌名排序",
			_7:"按歌手排序"
		}
	},
	en:{
		verify:{
			_1:"Return to QR code page",
			_2:"You are disconnected with the phone！",
			_3:"Phone",
			_4:"Scanning QR code successful",
			_5:"Request to connect is successful, please confirm on the phone！",
		},
		common:{
			_title:"Zapya WebShare",
			_date:"Date",
			_0:"You will delete selected files",
			_1:"Upload successful",
			_2:"Upload failed, please try again",
			_3:"Select All",
			_4:"Uploading, please wait...",
			_5:"You will delete selected photos",
			_6:"You will delete selected videos",
			_7:"You will delete selected audios",
			_8:"Confirm",
			_9:"Cancel",
			_10:"Close",
			_11:"Unable to delete, please check network connection!",
			_12:"You will delete selected files",
			_14:"Upload complete",
			_15:" files is being uploaded",
			_16:"Zapya",
			_17:"Reconnect",
		},
		button:{
			_0:"Batch Delete",
			_1:"Batch Download",
			_2:"Upload Photo",
			_3:"Upload Video",
			_4:"Upload Audio",
		},
		homepage:{
			_0:"My Device",
			_1:"Photo",
			_2:"Video",
			_3:"Audio",
			_4:"App & Game",
			_5:"File Explorer",
			_6:"Camera",
			_7:"支持拖曳上传"
		},
		device:{
			_0:"Now ",
			_1:"Total ",
			_2:"You are disconnected with the phone!",
		},
		images:{
			_0:"Album",
			_1:"Zapya",
			_2:"Misc",
			_3:"QQ",
			_4:"WeChat",
			_5:"Weibo",
			_6:"Screenshot",
			_7:"Bluetooth"
		},
		video:{
			_0:"Video",
			_1:"Viewing the format of this file is not supported yet",
		},
		audio:{
			_0:"Audio",
			_1:"Name",
			_2:"Artist",
			_3:"Duration",
			_4:"Type",
			_5:"Size",
			_6:"Reaching the top of current play list",
			_7:"Reaching the bottom of current play list",
			_8:"unknown",
			_9:"Album"
		},
		app:{
			_0:"Name",
			_1:"Size",
			_2:"App",
			_3:"Data",
			_4:"Select All",
			_5:"Batch Download",
			_6:"Upload Local App",
			_7:"Uninstall",
			_8:"Delete",
			_9:"App & Game",
			_10:"Importing app, please click Install on the phone.....",
			_11:"Loading App Failed",
			_12:"Please continue uninstall on the phone",
			_13:"Uninstall Failed",
			_14:"Import Failed",
			_15:"Download",
			_16:"App Size",
			_17:"Data Size",
			_18:"Cache Size",
			_19:"Version"
		},
		file:{
			_0:"File Type",
			_1:"Device Storage",
			_2:"Recent Files",
			_3:"Large Files",
			_4:"Compressed Files",
			_5:"Installation Files",
			_6:"Documents",
			_7:"Internal Storage",
			_8:"External Storage",
			_9:"Name",
			_10:"Path",
			_11:"Size",
			_12:"Type",
			_13:"Date",
			_14:"Select All",
			_15:"Delete",
			_16:"Batch Download",
			_17:"Upload File",
			_18:"New Folder",
			_19:"Importing file, please wait...",
			_20:"Delete Failed",
			_21:"Import Failed",
			_22:"Failed to create new folder",
			_23:"Folder name cannot be blank",
			_24:"A folder with the same name already exists",
			_25:"Dowload Failed",
			_26:"Download",
			_27:"Loading File Failed",
			_28:"Batch Delete",
			_29:"QQ",
			_30:"微信"
		},
		camera:{
			_0:"Failed to enable camera",
			_1:"Preview",
			_2:"Disable Preview",
			_3:"Enable Flash",
			_4:"Disable Flash",
			_5:"Operation failed",
			_6:"Photo capture successful",
			_7:"Photo capture failed",
			_8:"Capture",
			_9:"Reverse Lens",
			_10:"Settings",
			_11:"Save to PC",
			_12:"Save to Phone",
			_13:" Autofocus",
			_14:"Autofocus before capture",
			_15:"Setting successful",
			_16:"Setting failed",
			_17:"Send successful",
			_18:"Failed to send",
			_19:"Enable Notification",
			_20:"Disable Notification",
			_21:"Please Enable Preview and then click to capture photo!",
			_22:".If failed to enable camera, please grant access permission to Zapya WebShare in system app privilege settings, and also check if the camera is occupied by other apps.",
			_23:".Click on button at the lower right corner of camera interface to enable/disable camera.  Enabling camera here will deny access to camera by other apps.",
			_24:".Photos captured and saved to the phone can be viewed in the left navigation -> Album screen of the app.",
			_25:".The effect of monitoring and photo capturing depends on the camera and network quality.",
			_26:"Switch Lens",
			_27:"Help",
			_28:"Assist Line",
			_29:"Image Storage",
			_30:"Image Ratio",
			_31:"Flash",
			_32:"Image Quality",
			_33:"Raising image quality will lower viewing speed",
			_34:"Poor",
			_35:"Low",
			_36:"Average",
			_37:"Good",
			_38:"Excellent"
		},
		pasteboard:{
			_0:"Clipboard",
			_1:"Search",
			_2:"Send",
			_3:"Send content below to clipboard on the phone. Click on edit box below to paste content.",
			_4:"Open web page or search for content below in web browser on the phone",
			_5:"Search in browser",
			_6:"Clear"
		},
		message:{
			_0:"Total ",
			_1:" Messages",
			_2:"Click ",
			_3:"View",
			_4:"After enable Screen Notification in left navigation -> Settings on the phone, any notifications received by the phone will be shown here.",
			_5:"Notification Bar",
			_6:"After enable Screen Notification in left navigation -> Settings on the phone,Calls and messages received by the phone will be shown here.",
			_7:"Messages"
		},
		upload:{
			_0:"Drag & Drop files here to upload",
			_1:" File upload successful",
			_2:" File upload failed",
			_3:" Files upload successful",
			_4:" Files upload failed",
		},
		phone:{
			_0:"Edit",
			_1:"Home",
			_2:"File Upload",
			_3:"Home",
			_4:"Device Internal Storage",
			_5:"Store to remote device",
			_6:"Sort by name",
			_7:"Sort by artist"
		}
	},
	fa:{
		verify:{
			_1:"回到掃碼頁面",
			_2:"您已與手機斷開連接！",
			_3:"手機",
			_4:"掃描二維碼成功",
			_5:"請求連接成功，請在手機上確認！",
		},
		common:{
			_title:"快牙網傳",
			_date:"日期",
			_0:"您即將刪除所選檔案",
			_1:"上傳成功",
			_2:"上傳失敗，請重新嘗試",
			_3:"全選",
			_4:"上傳中，請稍候...",
			_5:"您即將刪除所選圖片",
			_6:"您即將刪除所選影片",
			_7:"您即將刪除所選音樂",
			_8:"確認",
			_9:"取消",
			_10:"關閉",
			_11:"刪除失敗，請檢查您的網路連線！",
			_12:"您即將刪除所選檔案",
			_13:"您的下載被瀏覽器阻擋，請設定地址欄出現的攔截設定",
			_14:"上傳完成",
			_15:"個檔案正在上傳",
			_16:"快牙官網",
			_17:"重新連接",
		},
		button:{
			_0:"批次刪除",
			_1:"批次下載",
			_2:"上傳圖片",
			_3:"上傳影片",
			_4:"上傳音樂",
		},
		homepage:{
			_0:"我的設備",
			_1:"圖片",
			_2:"影片",
			_3:"音樂",
			_4:"App遊戲",
			_5:"檔案管理",
			_6:"相機",
			_7:"支持拖曳上傳"
		},
		device:{
			_0:"當前",
			_1:"共",
			_2:"您已與手機斷開連接！",
		},
		images:{
			_0:"相冊",
			_1:"快牙",
			_2:"其他",
			_3:"QQ",
			_4:"微信",
			_5:"微博",
			_6:"螢幕抓圖",
			_7:"藍芽"
		},
		video:{
			_0:"影片",
			_1:"此影片格式暫不支援播放",
		},
		audio:{
			_0:"音樂",
			_1:"歌曲名",
			_2:"歌手",
			_3:"長度",
			_4:"格式",
			_5:"大小",
			_6:"當前播放列表已至最頂部",
			_7:"當前播放列表已至最底部",
			_8:"未知",
			_9:"專輯"
		},
		app:{
			_0:"名稱",
			_1:"大小",
			_2:"App",
			_3:"資料",
			_4:"全選",
			_5:"批次下載",
			_6:"上傳安裝包",
			_7:"卸載",
			_8:"刪除",
			_9:"App遊戲",
			_10:"App正在導入,請稍後在手機上安裝.....",
			_11:"App載入失敗",
			_12:"請在手機上完成卸載",
			_13:"卸載操作失敗",
			_14:"導入失敗",
			_15:"下載",
			_16:"安裝包大小",
			_17:"資料大小",
			_18:"記憶體大小",
			_19:"版本"
		},
		file:{
			_0:"檔案類別",
			_1:"儲存位置",
			_2:"最近檔案",
			_3:"大型檔案",
			_4:"壓縮檔案",
			_5:"安裝包",
			_6:"文件",
			_7:"內部記憶體",
			_8:"外部記憶卡",
			_9:"名稱",
			_10:"所在路徑",
			_11:"大小",
			_12:"類型",
			_13:"日期",
			_14:"全選",
			_15:"刪除",
			_16:"批次下載",
			_17:"上傳檔案",
			_18:"新建檔案夾",
			_19:"檔案正在導入，請稍候.....",
			_20:"刪除失敗",
			_21:"導入失敗",
			_22:"新建檔案夾失敗",
			_23:"檔案夾名字不能為空",
			_24:"檔案夾和已有檔案同名",
			_25:"下載失敗",
			_26:"下載",
			_27:"檔案載入失敗",
			_28:"批次刪除",
			_29:"QQ",
			_30:"微信"
		},
		camera:{
			_0:"打開相機失敗",
			_1:"預覽",
			_2:"停止預覽",
			_3:"開啓閃光燈",
			_4:"關閉閃光燈",
			_5:"操作失敗",
			_6:"拍照成功",
			_7:"拍照失敗",
			_8:"拍照",
			_9:"用反面的鏡頭",
			_10:"設定",
			_11:"儲存到電腦",
			_12:"儲存到手機",
			_13:"自動對焦",
			_14:"拍照前自動對焦",
			_15:"設定成功",
			_16:"設定失敗",
			_17:"發送成功",
			_18:"發送失敗",
			_19:"允許通知",
			_20:"禁止通知",
			_21:"請開啓預覽後按鈕拍照!",
			_22:"、如果打開相機失敗，請在手機系統App權限設定中允許快牙網傳使用相機，並查看相機是否被其它App所占用。",
			_23:"、點相機界面右下角的按鈕可以開啓／關閉相機，相機打開時，會導致其它App無法使用相機。",
			_24:"、拍照後，存到手機的照片可以在快牙網傳App的側邊欄的網傳相冊中查看。",
			_25:"、預覽、拍照的效果與相機、網路品質有關。",
			_26:"鏡頭切換",
			_27:"說明書",
			_28:"輔助線",
			_29:"照片儲存位置",
			_30:"照片比例",
			_31:"閃光燈",
			_32:"照片畫質",
			_33:"高畫質照片會降低預覽的流暢度",
			_34:"差",
			_35:"模糊",
			_36:"一般",
			_37:"較好",
			_38:"清晰"
		},
		pasteboard:{
			_0:"剪貼簿",
			_1:"搜尋",
			_2:"發送",
			_3:"發送內容到手機的剪貼簿，長按編輯區域可以貼上內容",
			_4:"在手機的瀏覽器中打開網頁或搜尋內容",
			_5:"在瀏覽器中打開",
			_6:"清除"
		},
		message:{
			_0:"共",
			_1:"條通知",
			_2:"點一下",
			_3:"查看",
			_4:"在快牙網傳App側邊欄的設定中開啓桌面通知服務後，手機收到的通知會顯示在這裏。",
			_5:"通知欄",
			_6:"在快牙網傳App側邊欄的設定中開啓桌面通知服務後，手機收到的來電、簡訊會顯示在這裏。",
			_7:"通知"
		},

		upload:{
			_0:"拖曳檔案到這裏上傳",
			_1:" 個檔案已上傳",
			_2:" 個檔案上傳失敗",
			_3:" 個檔案已上傳",
			_4:" 個檔案上傳失敗"
		},
		phone:{
			_0:"編輯",
			_1:"首頁",
			_2:"檔案上傳",
			_3:"主頁",
			_4:"手機記憶體",
			_5:"儲存到遠端設備",
			_6:"按歌名排序",
			_7:"按歌手排序"
		}
	},
	init:function(langCode){
		var langObj=zapya.langPkg[langCode];
		document.title=langObj.common._title;
		$("._lang").each(function(index, element) {
			var module=$(this).attr("data-lang").substring(0,$(this).attr("data-lang").indexOf("_"));
			var target=$(this).attr("data-lang").substring($(this).attr("data-lang").indexOf("_"));
			if(langObj[module]&&langObj[module][target]){
				$(this).text(langObj[module][target]);
			}
        });
	},
	setContent:function(dataTarget){
		var langCode=zapya.language;
		var langObj=zapya.langPkg[langCode];
		var module=dataTarget.substring(0,dataTarget.indexOf("_"));
		var target=dataTarget.substring(dataTarget.indexOf("_"));
		if(langObj[module]&&langObj[module][target]){
			return langObj[module][target];
		}
	},
};
